# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0CoRgJLeLaecLNSIBhWydpVsrG6DIH0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


np.random.seed(42)

n_students = 30
names = [f"Student {i+1}" for i in range(n_students)]
ages = np.random.randint(12, 14, n_students)
heights = np.round(np.random.normal(150, 10, n_students), 1)
weights = np.round(np.random.normal(45, 5, n_students), 1)
ffm = np.round(weights * np.random.uniform(0.7, 0.9, n_students), 1)
smm = np.round(weights * np.random.uniform(0.4, 0.6, n_students), 1)


run_10m_before = np.round(np.random.uniform(2.5, 3.0, n_students), 2)
run_3x10m_before = np.round(np.random.uniform(8.5, 10.0, n_students), 2)
long_jump_before = np.round(np.random.uniform(2.5, 3.5, n_students), 2)


group = ["Group 1" if i < n_students // 2 else "Group 2" for i in range(n_students)]


run_10m_after = run_10m_before - np.where(np.array(group) == "Group 1", np.random.uniform(0.1, 0.3, n_students), 0)
run_3x10m_after = run_3x10m_before - np.where(np.array(group) == "Group 1", np.random.uniform(0.2, 0.5, n_students), 0)
long_jump_after = long_jump_before + np.where(np.array(group) == "Group 1", np.random.uniform(0.1, 0.3, n_students), 0)


data = {
    "Name": names,
    "Group": group,
    "Age": ages,
    "Height (cm)": heights,
    "Weight (kg)": weights,
    "FFM (kg)": ffm,
    "SMM (kg)": smm,
    "Run 10m Before (s)": run_10m_before,
    "Run 10m After (s)": run_10m_after,
    "Run 3x10m Before (s)": run_3x10m_before,
    "Run 3x10m After (s)": run_3x10m_after,
    "Long Jump Before (m)": long_jump_before,
    "Long Jump After (m)": long_jump_after,
}

df = pd.DataFrame(data)


file_path = "/training_results (1).csv"
df.to_csv(file_path, index=False)


plt.figure(figsize=(14, 8))


plt.subplot(2, 2, 1)
plt.plot(names, run_10m_before, label='До тренировки', marker='o', linestyle='-', color='red')
plt.plot(names, run_10m_after, label='После тренировки', marker='o', linestyle='--', color='blue')
plt.xticks(rotation=90, fontsize=8)
plt.xlabel("Имя")
plt.ylabel("Время (с)")
plt.title("Бег на 10 метров")
plt.legend()

(Бег на 3/)
plt.subplot(2, 2, 2)
plt.plot(names, run_3x10m_before, label='До тренировки', marker='o', linestyle='-', color='red')
plt.plot(names, run_3x10m_after, label='После тренировки', marker='o', linestyle='--', color='blue')
plt.xticks(rotation=90, fontsize=8)
plt.xlabel("Имя")
plt.ylabel("Время (с)")
plt.title("Бег 3x10 метров")
plt.legend()


plt.subplot(2, 2, 3)
plt.plot(names, long_jump_before, label='До тренировки', marker='o', linestyle='-', color='red')
plt.plot(names, long_jump_after, label='После тренировки', marker='o', linestyle='--', color='blue')
plt.xticks(rotation=90, fontsize=8)
plt.xlabel("Имя")
plt.ylabel("Дистанция (м)")
plt.title("Прыжок в длину")
plt.legend()


plt.subplot(2, 2, 4)
plt.bar(names, heights, label='Рост (см)', alpha=0.6, color='green')
plt.bar(names, weights, label='Вес (кг)', alpha=0.6, color='purple')
plt.xticks(rotation=90, fontsize=8)
plt.xlabel("Имя")
plt.ylabel("Рост / Вес")
plt.title("Рост и вес учеников")
plt.legend()

plt.tight_layout()
plt.show()

file_path

